import './globals.css'
import Link from "next/link";
import Head from 'next/head'
import Image from 'next/image'
import styles from './Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Enzo Cheatsheet</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://github.com/Eynzof">Enzo</a>&apos;s Cheatsheet!
                </h1>

                <div className={styles.grid}>
                    <Link href='./grid' className={styles.card}><h2>Grid &rarr;</h2>
                        <p>Learn more about grid display</p>
                    </Link>

                    <Link href='./grid' className={styles.card}><h2>Flex &rarr;</h2>
                        <p>Learn more about flex display</p>
                    </Link>

                    <Link href='./grid' className={styles.card}><h2>Shortcuts &rarr;</h2>
                        <p>Learn more about flex display</p>
                    </Link>

                    <Link href='./grid' className={styles.card}><h2>Regex &rarr;</h2>
                        <p>Learn more about flex display</p>
                    </Link>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
                </a>
            </footer>
        </div>
    )
}
