import React from 'react';
import Header from "../src/components/Header/Header";
import Head from "next/head";
import styles from "../src/styles/grid.module.css";
import Line from "../src/components/Shortcut/Line";
import Footer from "../src/components/footer";

function Command() {
    return (
        <>
            <Head>
                <title>Command</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="stylesheet" href="https://unpkg.com/keyboard-css@1.2.4/dist/css/main.min.css"/>
            </Head>
            <Header />
            <div className={styles.main}>
            </div>
        </>
    );
}

export default Command;