import styles from '../src/styles/grid.module.css';
import Link from "next/link";
import React from "react";
import FlexDisplay from "../src/components/Flex/FlexDisplay";
import FlexDirection from "../src/components/Flex/FlexDirection";
import FlexWrap from "../src/components/Flex/FlexWrap";
import FlexJustifyContent from "../src/components/Flex/FlexJustifyContent";
import FlexAlignItems from "../src/components/Flex/FlexAlignItems";
import FlexAlignContents from "../src/components/Flex/FlexAlignContents";
import Footer from "../src/components/footer";
import FlexAxis from "../src/components/Flex/FlexAxis";
import Head from "next/head";

function Flex() {
    return (<>
        <Head>
            <title>Flex</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <h1 className={styles.title}><Link href={"/"} style={{fontSize: "32px"}}>←&nbsp;</Link>Flex</h1>
        <div className={styles.main}>
            <h2>Container</h2>
            <div className={styles.sets}>
                <FlexDisplay/>
                <FlexDirection/>
                <FlexAxis/>
                <FlexWrap/>
                <FlexAlignItems/>
                <FlexAlignContents/>
                <FlexJustifyContent/>
            </div>
            <Footer/>
        </div>
    </>)
}

export default Flex