import React from 'react';
import styles from "../src/styles/grid.module.css";
import GridTemplate from "../src/components/Grid/GridTemplate";
import GridGap from "../src/components/Grid/GridGap";
import Link from "next/link";
import JustifyItem from "../src/components/Grid/JustifyItem";
import AlignItem from "../src/components/Grid/AlignItem";
import JustifyContent from "../src/components/Grid/JustifyContent";
import AlignContent from "../src/components/Grid/AlignContent";
import GridDisplay from '../src/components/Grid/GridDisplay';
import GridAutoFlow from "../src/components/Grid/GridAutoFlow";
import Footer from "../src/components/footer";
import Head from "next/head";
import Header from "../src/components/Header/Header";
function Grid() {
    return (
        <>
            <Head>
                <title>Grid</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header />

            <div className="main">
                <h2>Container</h2>
                <div className="sets">
                    <GridDisplay />
                    <GridTemplate/>
                    <JustifyItem/>
                    <AlignItem/>
                    <JustifyContent/>
                    <AlignContent/>
                    <GridGap/>
                    <GridAutoFlow/>
                </div>
                <Footer/>
            </div></>
    );
}

Grid.propTypes = {};

export default Grid;