import React from 'react';
import styles from "../styles/grid.module.css";
import GridTemplate from "../components/Grid/GridTemplate";
import GridGap from "../components/Grid/GridGap";
import Link from "next/link";
import JustifyItem from "../components/Grid/JustifyItem";
import AlignItem from "../components/Grid/AlignItem";
import JustifyContent from "../components/Grid/JustifyContent";
import AlignContent from "../components/Grid/AlignContent";
import GridDisplay from '../components/Grid/GridDisplay';
import GridAutoFlow from "../components/Grid/GridAutoFlow";
import Footer from "../components/footer";
import Head from "next/head";
function Grid() {
    return (
        <>
            <Head>
                <title>Grid</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1 className={styles.title} ><Link href={"/"} style={{fontSize:"32px"}}>←&nbsp;</Link>GRID</h1>
            <div className={styles.main}>
                <h2>Container</h2>
                <div className={styles.sets}>
                    <GridDisplay />
                    <GridTemplate/>
                    <JustifyItem/>
                    <AlignItem/>
                    <JustifyContent/>
                    <AlignContent/>
                    <GridGap/>
                    <GridAutoFlow/>
                </div>
                <Footer/>
            </div></>
    );
}

Grid.propTypes = {};

export default Grid;