import React from 'react';
import styles from "../styles/grid.module.css";
import Link from "next/link";
import Footer from "../components/footer";
import Head from "next/head";

function ShortCut() {
    return (
        <>
            <Head>
                <title>Enzo Cheatsheet</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="stylesheet" href="https://unpkg.com/keyboard-css@1.2.4/dist/css/main.min.css"/>
            </Head>
            <h1 className={styles.title}><Link href={"/"} style={{fontSize: "32px"}}>←&nbsp;</Link>Shortcuts</h1>
            <div className={styles.main}>
                <h2>Web Storm</h2>
                <div className={styles.sets}>
                    <div className={styles.set} style={{display: 'flex', flexDirection: 'column'}}>
                        <div className={styles.header}>编辑器</div>
                        <div className={styles.lore}>
                            <p>在编辑器中对代码文本进行的操作</p>
                        </div>
                        <div className={styles.sections} style={{
                            display: 'grid',
                            gridTemplateColumns: '2fr 1fr',
                            alignItems: 'center',

                        }}>
                            <div>
                                <kbd className="kbc-button">Ctrl</kbd> + <kbd
                                className="kbc-button">Command</kbd> + <kbd
                                className="kbc-button">L</kbd>
                            </div>
                            <p style={{display: 'inline-block', fontSize: 20}}>格式化导入</p>
                        </div>

                    </div>
                </div>
                <Footer/>
            </div>
        </>
    );
}

ShortCut.propTypes = {};

export default ShortCut;