import React from 'react';
import styles from "../src/styles/grid.module.css";
import Link from "next/link";
import Footer from "../src/components/footer";
import Head from "next/head";
import Line from "../src/components/Shortcut/Line";
import Header from "../src/components/Header/Header";

function ShortCut() {
    return (
        <>
            <Head>
                <title>Shortcuts</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="stylesheet" href="https://unpkg.com/keyboard-css@1.2.4/dist/css/main.min.css"/>
            </Head>
            <Header />
            <div className={styles.main}>
                <h2>Web Storm</h2>
                <div className={styles.sets}>
                    <div className={styles.set} style={{display: 'flex', flexDirection: 'column'}}>
                        <div className={styles.header}>编辑器</div>
                        <div className={styles.lore}>
                            <p>在编辑器中对代码文本进行的操作</p>
                        </div>
                        <Line keys={["Command", "Option", "L"]} lore="格式化代码及导入"/>
                        <Line keys={["Ctrl", "Command", "L"]} lore="格式化导入"/>
                        <Line keys={["Ctrl", "D"]} lore="复制行"/>
                        <Line keys={["Command", "Delete"]} lore="删除行"/>
                        <Line keys={["Shift", "F6"]} lore="重命名变量"/>
                        <Line keys={["Command", "Shift", "A"]} lore="查找所有功能的快捷键"/>
                    </div>
                </div>
                <Footer/>
            </div>
        </>
    );
}

ShortCut.propTypes = {};

export default ShortCut;